spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ywesc
    username: root
    password: 123456

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

mybatis:
  type-aliases-package: com.example.ywcarapi.model
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
# PageHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql